/** VisionTrack.Domain.Enums.EventType — transcribed from the live Swagger UI
 *  (api.autonomise.ai/docs, captured 2026-06-12). Mirrors proxy/src/enums.ts. */

export const EVENT_TYPE_LABELS: Record<number, string> = {
  0: "Undefined",
  1: "Unknown",
  2: "Speed",
  3: "Brake",
  4: "Accelerate",
  5: "Shock",
  6: "Turn",
  7: "Button",
  8: "System",
  9: "Diagnostics",
  10: "Ignition On",
  11: "Ignition Off",
  12: "Video Request",
  13: "Fixed Speed",
  14: "GPS Fault",
  15: "Video Loss",
  16: "Storage Abnormal",
  17: "Camera Covered",
  18: "Fatigue",
  19: "Smoking",
  20: "Distraction",
  21: "No Driver",
  22: "Lane Departure",
  23: "Forward Collision Warning",
  24: "Left Hand Indicator",
  25: "Right Hand Indicator",
  26: "Vehicle Reversing",
  27: "Mobile Phone Warning",
  28: "Following Distance Warning",
  29: "Seatbelt Unfastened",
  30: "Pedestrian Collision",
  31: "Blind Spot Detection",
  32: "Black Event",
  33: "Blind Spot Detection Rear",
  34: "Blind Spot Detection Left",
  35: "Blind Spot Detection Front",
  36: "Blind Spot Detection Right",
  37: "Pedestrian Detection Rear",
  38: "Pedestrian Detection Left",
  39: "Pedestrian Detection Front",
  40: "Pedestrian Detection Right",
  41: "Pedestrian Detection",
  42: "Illegal Shutdown",
  43: "Solid Line Violation",
  44: "Privacy Glasses Detected",
  45: "Stop Sign Violation",
  46: "Right Side Intrusion",
  47: "Frequent Lane Changes",
  48: "Drowsy Eyes Detected",
  49: "Low Bridge Detected",
  50: "Physiological Fatigue",
};
